### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by eridgd** [sczhou/CodeFormer#1]
Very interesting work! When do you plan to make the code available?

**Comment by sczhou** [comment]
Thanks! We will release the test code and model in the next few days.

**Comment by sczhou** [comment]
@eridgd Thanks! We will release the test code and model in the next few days.

**Comment by 2blackbar** [comment]
That would be great, i have a lot of family photos that id like to test with this AI

**Comment by jmiran15** [comment]
Hey, when do you plan to release the code? Thanks!

**Comment by GifCo** [comment]
Hey guys. This project looks amazing! Are you still planning on releasing the code and model today? Would love to play around with it this weekend.

**Comment by sczhou** [comment]
Hi all @eridgd @2blackbar @jmiran15 @GifCo, 

We just release the test code and model for face restoration. 

Enjoy! :blush:

**Comment by vishal11110** [comment]
![Uploading out (2).png…]()
