### ISSUE TITLE
It says that video is generated but actually no folder in result why

### ISSUE THREAD

**Issue by kingwang98** [sczhou/CodeFormer#108]
Hi Video clip does not work for me no folder created.   Created once but after that never again.

**Comment by kingwang98** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4281713/213142795-c94a85a9-a050-4df7-8332-62860f9c1ed8.png">

**Comment by kingwang98** [comment]
supposed to have a video folder as output

**Comment by sczhou** [comment]
The `input_path` should end up with '.mp4/.avi' for the video inputs.
