### ISSUE TITLE
on M1 module not found

### ISSUE THREAD

**Issue by ada1016** [sczhou/CodeFormer#111]
(codeformer) stevenj@StevenJdeMacBook-Pro CodeFormer % python inference_codeformer.py -w 0.7 --input_path ./inputs/TestWhole
Traceback (most recent call last):
  File "inference_codeformer.py", line 9, in <module>
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
ModuleNotFoundError: No module named 'facelib.utils'
(codeformer) stevenj@StevenJdeMacBook-Pro CodeFormer % pip3 install facelib
ERROR: Ignored the following versions that require a different python version: 1.0 Requires-Python >=3.5, <3.8; 1.1 Requires-Python >=3.5, <3.8; 1.2 Requires-Python >=3.5, <3.8; 1.2.1 Requires-Python >=3.5, <3.8
ERROR: Could not find a version that satisfies the requirement facelib (from versions: none)
ERROR: No matching distribution found for facelib
(codeformer) stevenj@StevenJdeMacBook-Pro CodeFormer % 

I am new and on M1 macbookpro, I tried to install facelib myself and does not work either. How to fix this error?

**Comment by sczhou** [comment]
No additional installation is needed for facelib, as it is already included in the project. So please ensure that your CodeFormer code is complete and should contain the facelib folder. 

If the code is complete, it is recommended that you create a new virtual Conda environment and try reinstalling following the steps in this link: https://github.com/sczhou/CodeFormer#dependencies-and-installation

**Comment by ada1016** [comment]
thank you! issue resolved.
