### ISSUE TITLE
Is it possible to use RealESRGAN_x4plus model for RealESRGAN

### ISSUE THREAD

**Issue by fong123** [sczhou/CodeFormer#115]
![image](https://user-images.githubusercontent.com/14935284/213866068-ae5181e4-f29f-4e63-81f8-9a01848cf2b4.png)

Currently the project is using RealESRGAN_x2plus model, and I found that the RealESRGAN_x4plus model perform much more quality for background enhancement.
When i switch to x4plus model, I get this error
![image](https://user-images.githubusercontent.com/14935284/213866261-ff3b9d7a-e010-4ba2-a6d9-d2379f2832d6.png)

So, is there anyway to adopt the x4plus model into this project?

**Comment by AndreiBulzan** [comment]
Hey fong, what worked for me was setting scale to 4 on both RealESRGANer and RRDBNet.
