### ISSUE TITLE
What performance to expect on M1 2021?

### ISSUE THREAD

**Issue by ada1016** [sczhou/CodeFormer#118]
I'd like to know how to best utilise my 2021 M1 MBP for video processing. The M1 GPU is an integrated one so I don't think it can be as powerful as stand alone GPU. 

I tired 320*240 264Kbps avi file, (21m07s)

and it took me 30+ mins.   is that kind of expected or something didn't go properly?

thanks

**Comment by sczhou** [comment]
The 21m07s test video is excessively lengthy, with the potential for over 30,000 frames if the frame rate is assumed to be 25fps. This would require our model to perform 30,000 inferences, one per frame, which is why the long processing time of 30+ minutes is reasonable.

**Comment by Sojeebahamed** [comment]
![Uploading IMG_20230203_165851.jpg…]()

**Comment by Sojeebahamed** [comment]
Sojeeb

**Comment by Sojeebahamed** [comment]
Sojeeb
