### ISSUE TITLE
inference_codeformer.py returned an unrecognized parameter

### ISSUE THREAD

**Issue by xiaolang147258** [sczhou/CodeFormer#119]
usage: inference_codeformer.py [-h] [--w W] [--upscale UPSCALE] [--test_path TEST_PATH] [--has_aligned]
                               [--only_center_face] [--detection_model DETECTION_MODEL] [--draw_box]
                               [--bg_upsampler BG_UPSAMPLER] [--face_upsample] [--bg_tile BG_TILE]
inference_codeformer.py: error: unrecognized arguments: -w 0.7 --input_path E:\CodeFormer\inputs\whole_imgs

**Comment by xiaolang147258** [comment]
python = 3.10.8

**Comment by sczhou** [comment]
Your code seems old version, please download the latest one.
