### ISSUE TITLE
Is the training data for the codebook contains the GT of the test data?

### ISSUE THREAD

**Issue by tachikoma777** [sczhou/CodeFormer#12]
In Figure 1, the code GT is give, which is great. And the codeformer result looks pretty good too.  Just asking, the training data for the codebook does not contains the GT of this picture, right?

**Comment by sczhou** [comment]
The sample in Figure 1 is from the CelebA-HQ, while we train the codebook and CodeFormer only on FFHQ. CodeFormer actually has good generalizability for different datasets, even for real LQ images.

**Comment by tachikoma777** [comment]
thank you for explanation! One more question, the Fig1(b), what are the six classes of the t-sne clustering results? I guess one of them is the eyes or right eye?

**Comment by sczhou** [comment]
Sorry for missing this question, the six classes are six random code items from the 1024 codebook, we cannot make sure which parts of the faces they represent. Please note that we provided the eye image patches here just for a more intuitive understanding. Thanks.

**Comment by tachikoma777** [comment]
Hi @sczhou , i still have a question, i understand the tsne result is for a more intuitive understanding. May I ask what's the LQ and HQ data in the tsne experiment？ How many are them?
