### ISSUE TITLE
dlib as a main face tool

### ISSUE THREAD

**Issue by zetyquickly** [sczhou/CodeFormer#122]
Hello,

Thank you for your great work.
I've noticed some traces of DLIB in your repo, can you give an advice how one can replace facelib with DLIB in that repo?

**Comment by sczhou** [comment]
Hi @zetyquickly, I'm going to add back the option for using `dlib` as a face detector. Although it may be slower, it has been found that it produces better results that keep better identity consistency. Please stay tuned!

**Comment by RaYHaNLoveRuBi07** [comment]
![Uploading BeautyPlus_20230131185201319_save.jpg…]()

**Comment by RaYHaNLoveRuBi07** [comment]
Not working

**Comment by zetyquickly** [comment]
@RaYHaNLoveRuBi07 you haven't uploaded image successfully

**Comment by sczhou** [comment]
Hi @zetyquickly , now you can set `--detection_model dlib` in your command and have a try!

**Comment by zetyquickly** [comment]
@sczhou thank you! I'll have a try

**Comment by vincentmakayama** [comment]
First of all, excellent work! Getting great results.
I´m trying DLIB on my Macbook Air M2, but get the error ´Illegal instruction: 4´
Any idea why?

<img width="1259" alt="Screenshot 2023-02-17 at 17 57 35" src="https://user-images.githubusercontent.com/19371480/219716178-ef2d7b8d-18a4-4074-8471-64a94d842edf.png">
