### ISSUE TITLE
`--face_upsample` does nothing.

### ISSUE THREAD

**Issue by bolshoytoster** [sczhou/CodeFormer#124]
Looking through `inference_codeformer.py`, it seems that the `--face_upsample` flag is disabled for some reason:
https://github.com/sczhou/CodeFormer/blob/4c93a0ac8e309cb186165eba098fb8a379f9e349/inference_codeformer.py#L125-L132

It looks like this happened in [this commit](https://github.com/sczhou/CodeFormer/commit/396b5e1d92022ed776ed3d3174e26fd330ed0f74) enabling CPU support for realesrgan.

Is there a reason this should be disabled or was it just commented out during debugging and not uncommented afterwards?

**Comment by sczhou** [comment]
Thanks for your kind reminding. I forgot to uncomment it after debugging.
Have fixed it now :hugs:
