### ISSUE TITLE
Can anyone tell me how to install and run this locally? 

### ISSUE THREAD

**Issue by Ka665** [sczhou/CodeFormer#139]
HI Everybody
  Can anyone tell me how to install and run this locally?  so difficult to run it. i downloard zipfile but no idea how to run it locally. any information can helpe me ? thank you

**Comment by sczhou** [comment]
Please check out the Readme file, it's very easy to run only by two steps:
Step 1: installation 
https://github.com/sczhou/CodeFormer#dependencies-and-installation

Step 2: inference (you can skip steps of downloading pre-trained models, they can be downloaded automatically when you run the inference commands)
https://github.com/sczhou/CodeFormer#quick-inference
