### ISSUE TITLE
Discriminator used in training

### ISSUE THREAD

**Issue by andreaferretti** [sczhou/CodeFormer#15]
Hi @sczhou , first let me thank you for your impressive work!

While reading the paper, I noticed that there are no details about the kind of discriminator that you used, it is just mentioned that you used an adversarial loss without further information. Could you share some information about this?

**Comment by sczhou** [comment]
Hi @andreaferretti, thanks.

We used patch discriminator for our Stages I and III, I added the discriminator code for your reference, you can find it here: 
https://github.com/sczhou/CodeFormer/blob/master/basicsr/archs/vqgan_arch.py#L396

**Comment by andreaferretti** [comment]
Great, thank you for the prompt response!
