### ISSUE TITLE
How do I make the collab work with my own pictures?

### ISSUE THREAD

**Issue by MrGoatsy** [sczhou/CodeFormer#16]
I tried looking for the folder, but I can't find it.

**Comment by sczhou** [comment]
You can find the results in the left sidebar of Colab. (CodeFormer/results/user_upload_0.7/final_results)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/14334509/185779471-29a90718-2635-4da8-abec-3b9bea5f2c14.png">

**Comment by sczhou** [comment]
OR you can run this 'download' block to download your results.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/14334509/185779887-8bedb9c2-a79f-488e-ace9-7db13f3a5f01.png">
