### ISSUE TITLE
M2 Pro 16GB Ram failed processing video

### ISSUE THREAD

**Issue by SauChi666** [sczhou/CodeFormer#172]
Hi, video processing stopped, and show this...   zsh: segmentation fault  python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w  I notice my memory gone half way and then come back down... The mp4 file is only 35MB, Python version 3.9, Thanks in advance!

**Comment by SauChi666** [comment]
Solved... https://medium.com/mlearning-ai/install-tensorflow-on-mac-m1-m2-with-gpu-support-c404c6cfb580

**Comment by DaleAndriy** [comment]
thx ，article is not free  😂
`pip install tensorflow-macos`
`pip install tensorflow-metal`
