### ISSUE TITLE
Face Detection Help

### ISSUE THREAD

**Issue by surrealism7x** [sczhou/CodeFormer#19]
Scenario: Having 512x512 image created by AI where the face only makes up 5-10% of the image.
It does not detect the face. So I'm cropping the face in Photoshop and reloading it to CodeFormer (It now detects the face), afterwards loading it to Photoshop again to blend it with the original image. It works well but lots of manual work.

Would it be possible to create some kind of interactive selection to guide/assist/help CodeFormer?
Imagine creating some kind of square selection over the image, now it crops automatically that area, uses that for the restoration. Then after the restoration it adds the cropped image on top of the original image again. + Upscaling if needed.

**Comment by caacoe** [comment]
Have you tried switching to the retina model in source? I have detection issues for AI created images with the default model

**Comment by surrealism7x** [comment]
Thanks for your fast answer! I am using your colab. Where do I switch the model there?

**Comment by caacoe** [comment]
I'm using it locally on my pc but I assume there's the same line of code somewhere with a comment referencing retina50 or something to that affect, you just need to replace the line of code in quotation marks with the model listed in the comment

**Comment by caacoe** [comment]
That's correct

**Comment by surrealism7x** [comment]
It works, but it still did not detect the face.. 

`Downloading: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth" to /content/CodeFormer/weights/realesrgan/RealESRGAN_x2plus.pth

100% 64.0M/64.0M [00:04<00:00, 13.5MB/s]
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to /content/CodeFormer/weights/facelib/detection_Resnet50_Final.pth

100% 104M/104M [00:00<00:00, 252MB/s]
Processing: 3.png
	detect 0 faces

All results are saved in results/user_upload_0.7`

**Comment by caacoe** [comment]
Can you share the image?

**Comment by surrealism7x** [comment]
Sure. Add me on Discord. Trebz#6866
