### ISSUE TITLE
How can I train in my own dataset?

### ISSUE THREAD

**Issue by hongsiyu** [sczhou/CodeFormer#2]
I am happy to inference using this excellent works.  Please release the training code as soon as possible.

**Comment by modcomper** [comment]
Agreed, thanks for releasing! Had a lot of fun using this over the weekend - great stuff 

I was also wondering if you plan to release training code any time? 
And if the current 512x512 output res will be pushed higher in future releases?

**Comment by sczhou** [comment]
Hi all, thanks for your big interest in this work. 

This paper is under review now, thus, we plan to release the training code and other models once the paper is accepted. 

Please stay tuned!

**Comment by sczhou** [comment]
Hi all, thanks for your big interest in this work.

This paper is under review now, thus, we plan to release the training code and other models once the paper is accepted.

Please stay tuned :)
