### ISSUE TITLE
How to remove scratches during old photo enhancement

### ISSUE THREAD

**Issue by hktalent** [sczhou/CodeFormer#201]
This is the result of processing with the following command
```
python inference_codeformer.py -w 0.7 --bg_upsampler realesrgan --face_upsample --input_path $HOME/MyWork/oldp/IMG_2061.PNG
```
<img width="458" alt="image" src="https://user-images.githubusercontent.com/18223385/231337617-65c6dc88-a931-4c8a-b160-f520e0ffdb54.png">

But this is not the expected goal and the output of arts，how fix it, thanks

**Comment by hktalent** [comment]
thanks

**Comment by Ap1075** [comment]
@hktalent were you able to do this? Please share your approach

**Comment by hktalent** [comment]
@Ap1075 Sorry, I can't. I've been looking for a solution to the issue
