### ISSUE TITLE
Stage3 load pretrained D weights trained in stage2 ？？

### ISSUE THREAD

**Issue by kaka45inablink** [sczhou/CodeFormer#214]
Great job! However, I'm having difficulty reproducing stage 3, and I'm feeling even more confused after reviewing your training configurations and code. I would greatly appreciate your response.

https://github.com/sczhou/CodeFormer/blob/8e2cd9b1983cf9d4af712133b1eb768f4ff4b3b2/options/CodeFormer_stage3.yml#L82

**Comment by YilanWang** [comment]
stage1.

**Comment by KaKaChan** [comment]
thanks for your reply，but it says clearly " pretrained D model in StageII "

**Comment by KaKaChan** [comment]
> stage1.

thanks for your reply，but it says clearly " pretrained D model in StageII "。
Have you reproduced stage3 with pretrained D model in StageII？

**Comment by Liar-zzy** [comment]
pretrain_network_d in CodeFormer_stage3.yml refers to [vqgan_discriminator.pth](https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/vqgan_discriminator.pth), which is pre trained in stage 1 as the discriminator.

**Comment by YilanWang** [comment]
> > stage1.
> 
> thanks for your reply，but it says clearly " pretrained D model in StageII "。 Or have you reproduced stage3 with pretrained D model in Stage1？

I think it is a typo……

**Comment by kaka45inablink** [comment]
Hmm, hard to say . "stage2" also in the pretrain_network_d path

**Comment by jameelhassan** [comment]
Hi, 
Did you get a good performance after training in Stage 3? Also, how exactly did you go about training only stage 3? Which pre-trained weights did you use for Network_G? Did you simply fine-tune over the existing Codeformer weights?

**Comment by kaka45inablink** [comment]
> Hi, Did you get a good performance after training in Stage 3? Also, how exactly did you go about training only stage 3? Which pre-trained weights did you use for Network_G? Did you simply fine-tune over the existing Codeformer weights?

Mainly use the same degradation type and set different degree of degradation as author

**Comment by jameelhassan** [comment]
Thanks for the reply. 

Did you train all 3 stages by yourself? Or did you only train Stage 3?

**Comment by kaka45inablink** [comment]
I trained all three stages from scratch, but I did not achieve satisfactory results until I began using the same degradation type and parameters as specified by the author.

**Comment by jameelhassan** [comment]
I am using the degradation type and parameters in the pushed codebase as of now. Is that what you are referring to?

Could you also share the model weights after Stage 2 training if possible?
I have tried training Stage 2, using the Stage 1 weights provided. I prepare the dataset by using the ```crop_and_align.py ``` script to resize the FFHQ 1024x1024 images to 512x512. Other than that, there have been no modifications made. But the performance of the model after Stage 2 training with ```w=0``` for inference is not at all satisfactory.

**Comment by kaka45inablink** [comment]
Degradation：
https://github.com/sczhou/CodeFormer/blob/4724c90b6b9d5183da383f2bdae6ddf9b0bf045d/basicsr/data/ffhq_blind_joint_dataset.py#L73
https://github.com/sczhou/CodeFormer/blob/4724c90b6b9d5183da383f2bdae6ddf9b0bf045d/basicsr/models/codeformer_joint_model.py#L153

I reproduced the training code by myself, so I didn't end up using the author's code for training. I am OK for stage 2.  Maybe you should open a new issue for help ...

**Comment by jameelhassan** [comment]
Oh okay. Thanks. 
I have opened a separate issue, waiting for a reply.

**Comment by kaka45inablink** [comment]
At that time, the author had not released the code yet.

**Comment by jameelhassan** [comment]
Is it possible to share the model weights after Stage 2 training? That would be great to compare it with the original codebase training model output. Thanks
