### ISSUE TITLE
Training Stage1 Problem

### ISSUE THREAD

**Issue by yueyue1009** [sczhou/CodeFormer#221]
Thanks for your excellent work! 
I have encountered a problem when training my own model on FFHQ 70000 512x512 images on my machine with two V100 GPU. 

In `options/VQGAN_512_ds32_nearest_stage1.yml`, I've changed `num_gpu` option to 2, and using following command to start training:
`python -m torch.distributed.launch --nproc_per_node=2 --master_port=4321 basicsr/train.py -opt options/VQGAN_512_ds32_nearest_stage1.yml --launcher pytorch`

However, it seems that the estimated time is almost the same (total 16 days) when using only one GPU. I also checked that there are really two process running on the two GPUs respectively. 

Is there anything I have to modify to make it work properly? Or maybe some advices to solve the problem. Thanks!

**Comment by Roller44** [comment]
Did you download the whole FFHQ dataset (with a size of 2.56 TB) and place it into "datasets/ffhq/ffhq_512"?
