### ISSUE TITLE
Can change saved filename?

### ISSUE THREAD

**Issue by readydave** [sczhou/CodeFormer#224]
I hope this is the right area to request this. If not, please feel free to point me in the right direction as this is my first time.

Would it be possible to have the default file name for the output match the name of the input file with an underscoreCF at the end? For example, let's say I input a file called **myfile123.png**. When it transforms and the final output is ready, I would like it to save or download the file and name it **myfile123_CF.png**. That would make it much easier to find and compare images in the folder where the images are saved. Currently, the file is saved as **out.png**, **out(1).png**, etc., when there are multiples of the same file name.

Thanks!

**Comment by sebaro** [comment]
Use "--suffix" argument:
-i image.png --suffix new => image_new.png

**Comment by sebaro** [comment]
```
img_name = os.path.basename(str(image))
basename, ext = os.path.splitext(img_name)
save_path = f'output/{basename}_CF{ext}'
imwrite(restored_img, str(save_path))
```

**Comment by readydave** [comment]
@sebaro thank you! 

I am running this inside of a Docker container. I drag and drop a local photo into Code Former in the web browser and that gives the file a different name that begins with **tmp**. When it is done, it's saving the file as tmpXXXXXX_cr.png. This works since the tmp files have different names every time. I am not sure where, in the code, it would set the tmp prefix, but this will work for my workflow. Thanks again!

**Comment by sebaro** [comment]
The web part is not in this repository, what do you use for the docker container?
