### ISSUE TITLE
Trained Inpainting Model is NOT Usable

### ISSUE THREAD

**Issue by Bai426** [sczhou/CodeFormer#250]
Hi, authors, I used the training codes and configure file to train an inpainting model, but the model is not readable in the testing step:

python inference_inpainting.py --input_path /home/neural_image/CodeFormer/inputs/masked_faces

[NOTE] The input face images should be aligned and cropped to a resolution of 512x512.
Traceback (most recent call last):
  File "inference_inpainting.py", line 53, in <module>
    net.load_state_dict(checkpoint)
  File "/home/neural_image/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CodeFormer:
	size mismatch for quantize.embedding.weight: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([512, 256]).
	size mismatch for idx_pred_layer.1.weight: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).

Please let me know how to proceed to next step.
 Best,
Mike

**Comment by iHateTa11B0y** [comment]
It looks like a configuration mistake. Check `codebook_size` in the inference script. `codebook_size` should be 1024 instead of 512 to match the model you trained

**Comment by Bai426** [comment]
Thank you for your reply. I change the codebook_size from 512 to 1024, but it still give error:
python inference_inpainting.py --input_path /home/neural_image/CodeFormer/inputs/masked_faces

[NOTE] The input face images should be aligned and cropped to a resolution of 512x512.
Traceback (most recent call last):
  File "inference_inpainting.py", line 54, in <module>
    net.load_state_dict(checkpoint)
  File "/home/neural_image/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CodeFormer:
	size mismatch for quantize.embedding.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for idx_pred_layer.1.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([1024, 512]).
