### ISSUE TITLE
Stage 3 iteration 120k error

### ISSUE THREAD

**Issue by jameelhassan** [sczhou/CodeFormer#251]
In Stage 3 training at iteration 120k the following error occurs
`RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`
It is in line 222 of codeformer_joint_model.py. It seems to occur because w=0 for this iteration and therefore the Lq features and the CFT module are not used, but the `torch.autograd.grad` is called on the last fused layer.

Can I know how this has to be handled? It is the original codebase, but the error pops up at this stage always.

**Comment by kaka45inablink** [comment]
Hi, you can try to set w>=0:
https://github.com/sczhou/CodeFormer/blob/4724c90b6b9d5183da383f2bdae6ddf9b0bf045d/basicsr/archs/codeformer_arch.py#L276

**Comment by jameelhassan** [comment]
Cool, I Will try that.

**Comment by create-li** [comment]
I also encountered the same mistake. Modifying **w>=0** or reporting an error. It's because I saved the weights from the previous one, which is 115k iterations of pre training. Do we need to retrain from the 0th iteration?
