### ISSUE TITLE
CodeFormer ONNX for AMD gpu

### ISSUE THREAD

**Issue by JohnC05** [sczhou/CodeFormer#252]
Hi,
Is it possible to have onnx conversion and inference code for AMD gpu on windows?
I tried to convert codeformer.pth to onnx to use it with torch-directml,
onnxruntime-directml for AMD gpu and It worked and very fast.
But the problem is the fidelity_weight "w" is being constant while converted, so the onnx file is smaller.
During inference fidelity_weight becomes 0 and resulted in dissimilar face than input.
I have no clue how to fix this same error in vqgan_arch.py: line 215, codeformer_arch.py: line 244, 260, 262, 273
```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
```
`w_ = w_ * (int(c)**(-0.5))`
`if code_only: # for training stage II`
`if detach_16:`
`if adain:`
`if w>0:`

I don't know how to add this "w" in input parameter. I have used this code to convert pth model to onnx.
`
model = CodeFormer(dim_embd=512, n_head=8, n_layers=9, codebook_size=1024, latent_size=256, connect_list=['32', '64', '128', '256'], fix_modules=['quantize','generator'])`

and for inference i used this code without "w"
```
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(cropped_face_t) }
ort_outs = ort_session.run(None, ort_inputs)
```
Can anyone help me understand what's gone wrong during conversion to onnx? and how to fix it?

I am trying to learn the new olive-ai[directml] which i suppose might solve it and optimize even further with speed.

**Comment by Mayorc1978** [comment]
I'm not sure about this, but from what I have seen onnx models get some parameter baked, so if you find a way, you could try create 3 different models to use occasionally, one with high fidelity 0.8 - 1.0 (0.9 for mid spot), one with mid 0.4-0.6 (0.5 mid) and one with low fidelity but higher quality at 0.2. They are usually smaller and faster to load, so could be the way to go, but you have to find a way to bake them inside the model.

**Comment by Mayorc1978** [comment]
I'm not sure about this, but from what I have seen onnx models get some parameter baked, so if you find a way, you could try create 3 different models to use occasionally, one with high fidelity 0.8 - 1.0 (0.9 for mid spot), one with mid 0.4-0.6 (0.5 mid) and one with low fidelity but higher quality at 0.2. They are usually smaller and faster to load, so could be the way to go, but you have to find a way to bake them inside the model.

**Comment by redthing1** [comment]
How do you set that W during conversion then?

**Comment by redthing1** [comment]
@JohnC05 did you manage to figure it out?

**Comment by redthing1** [comment]
I think I figured it out. I made an onnx that takes `w` as a parameter.

**Comment by redthing1** [comment]
Here's a working demo.
https://github.com/redthing1/CodeFormer/blob/master/inference_codeformer_onnx.py#L188

onnx conversion that takes w as a parameter. I also have separate code that does inference on onnx using numpy only and not torch; but it's not included here.

**Comment by redthing1** [comment]
Here's the `numpy` and `cv2` only inference code for onnx:

```sh
from io import BytesIO

import numpy as np
import onnxruntime

import cv2


class CodeFormer:
    def __init__(self, model_file=None, session_kwargs={}):
        self.model_file = model_file
        self.session = onnxruntime.InferenceSession(self.model_file, **session_kwargs)

    def infer(self, img, fidelity):
        if img.shape != (128, 128, 3):
            raise ValueError("Image must be 128x128")

        img = img.astype(np.float32)

        img = cv2.resize(img, (512, 512), interpolation=cv2.INTER_LINEAR)
        img = img / 255.0
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = img.transpose((2, 0, 1))

        nrm_mean = np.array([0.5, 0.5, 0.5]).reshape((-1, 1, 1))
        nrm_std = np.array([0.5, 0.5, 0.5]).reshape((-1, 1, 1))
        img = (img - nrm_mean) / nrm_std

        img = np.expand_dims(img, axis=0)

        model_inputs = self.session.get_inputs()
        inference_inputs = {
            model_inputs[0].name: img.astype(np.float32),
            model_inputs[1].name: np.array([fidelity], dtype=np.double),
        }
        inference_outputs = self.session.run(None, inference_inputs)

        output_img = inference_outputs[0]

        output_img = np.squeeze(output_img, axis=0)
        output_img = output_img.transpose((1, 2, 0))

        un_min = -1.0
        un_max = 1.0
        output_img = np.clip(output_img, un_min, un_max)
        output_img = (output_img - un_min) / (un_max - un_min)

        output_img = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)
        output_img = (output_img * 255.0).round()
        output_img = output_img.astype(np.uint8)

        return output_img

```

**Comment by Baiyixuan1113** [comment]
> Here's the `numpy` and `cv2` only inference code for onnx:
> 
> ```python
> from io import BytesIO
> 
> import numpy as np
> import onnxruntime
> 
> import cv2
> 
> 
> class CodeFormer:
>     def __init__(self, model_file=None, session_kwargs={}):
>         self.model_file = model_file
>         self.session = onnxruntime.InferenceSession(self.model_file, **session_kwargs)
> 
>     def infer(self, img, fidelity):
>         if img.shape != (128, 128, 3):
>             raise ValueError("Image must be 128x128")
> 
>         img = img.astype(np.float32)
> 
>         img = cv2.resize(img, (512, 512), interpolation=cv2.INTER_LINEAR)
>         img = img / 255.0
>         img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
>         img = img.transpose((2, 0, 1))
> 
>         nrm_mean = np.array([0.5, 0.5, 0.5]).reshape((-1, 1, 1))
>         nrm_std = np.array([0.5, 0.5, 0.5]).reshape((-1, 1, 1))
>         img = (img - nrm_mean) / nrm_std
> 
>         img = np.expand_dims(img, axis=0)
> 
>         model_inputs = self.session.get_inputs()
>         inference_inputs = {
>             model_inputs[0].name: img.astype(np.float32),
>             model_inputs[1].name: np.array([fidelity], dtype=np.double),
>         }
>         inference_outputs = self.session.run(None, inference_inputs)
> 
>         output_img = inference_outputs[0]
> 
>         output_img = np.squeeze(output_img, axis=0)
>         output_img = output_img.transpose((1, 2, 0))
> 
>         un_min = -1.0
>         un_max = 1.0
>         output_img = np.clip(output_img, un_min, un_max)
>         output_img = (output_img - un_min) / (un_max - un_min)
> 
>         output_img = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)
>         output_img = (output_img * 255.0).round()
>         output_img = output_img.astype(np.uint8)
> 
>         return output_img
> ```

Hi,

Thank you for sharing.

Does the onnx model file obtained using your transformation method support CPU inference only?

**Comment by JohnC05** [comment]
> Here's a working demo. https://github.com/redthing1/CodeFormer/blob/master/inference_codeformer_onnx.py#L188
> 
> onnx conversion that takes w as a parameter. I also have separate code that does inference on onnx using numpy only and not torch; but it's not included here.

Thank you, it works perfectly,
now the onnx file is equal to size the original pth file,
output image is accepting the dynamic fidelity_weight "w" as 2nd input,
pth output image and and onnx are producing same desired results.

With multiprocessing this onnx version producing 10~20 images per second on AMD 8GB card.
Whereas before it was only 2 images/s with pth. I wonder what kind of speed i will get olive, exciting!.

**Comment by instant-high** [comment]
exporting to codeformer.onnx does not work for me.

error message is:
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type float

using line 191 : (cropped_face_t,)
instead of line 192 : (cropped_face_t,w)
writes the onnx file, but a bit smaller than the .pth

When I try to run inference using that smaller onnx file using:
ort_inputs = {ort_session.get_inputs()[0].name: cropped_face_t.cpu().numpy(),ort_session.get_inputs()[1].name: torch.tensor(w).double().cpu().numpy(),}


Running CodeFormer ONNX...
Traceback (most recent call last):
  File "mini.py", line 92, in <module>
    ort_inputs = {ort_session.get_inputs()[0].name: cropped_face_t.cpu().numpy(),ort_session.get_inputs()[1].name: torch.tensor(w).double().cpu().numpy(),}
IndexError: list index out of range

Trying to run
ort_inputs = {ort_session.get_inputs()[0].name: cropped_face_t.cpu().numpy()}

**Comment by heorhiikalaichev** [comment]
This onnx model is able to process only aligned images?

**Comment by henryruhs** [comment]
Save your time:

```python
import torch
from basicsr.utils.registry import ARCH_REGISTRY

if __name__ == '__main__':
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    net = ARCH_REGISTRY.get('CodeFormer')(dim_embd=512, codebook_size=1024, n_head=8, n_layers=9, connect_list=['32', '64', '128', '256']).to(device)

    ckpt_path = 'weights/CodeFormer/codeformer.pth'
    checkpoint = torch.load(ckpt_path, map_location=device)['params_ema']
    net.load_state_dict(checkpoint)
    net.eval()

    input_tensor = torch.zeros((1, 3, 512, 512)).to(device)
    torch.onnx.export(net,
        (input_tensor, 1.0),
        "weights/CodeFormer/codeformer.onnx",
        export_params=True,
        opset_version=11,
        do_constant_folding=True,
        input_names=['x', 'w'],
        output_names=['y'],
    )
``

**Comment by Royalvice** [comment]
> > Save your time:
> > ```python
> > import torch
> > from basicsr.utils.registry import ARCH_REGISTRY
> > 
> > if __name__ == '__main__':
> >     device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
> >     net = ARCH_REGISTRY.get('CodeFormer')(dim_embd=512, codebook_size=1024, n_head=8, n_layers=9, connect_list=['32', '64', '128', '256']).to(device)
> > 
> >     ckpt_path = 'weights/CodeFormer/codeformer.pth'
> >     checkpoint = torch.load(ckpt_path, map_location=device)['params_ema']
> >     net.load_state_dict(checkpoint)
> >     net.eval()
> > 
> >     input_tensor = torch.zeros((1, 3, 512, 512)).to(device)
> >     torch.onnx.export(net,
> >         (input_tensor, 1.0),
> >         "weights/CodeFormer/codeformer.onnx",
> >         export_params=True,
> >         opset_version=11,
> >         do_constant_folding=True,
> >         input_names=['x', 'w'],
> >         output_names=['y'],
> >     )
> > ``
> > ```
> 
> I encountered this problem using your code. How to solve it? Thank you very much for your code. torch.onnx.export( File "d:\code\CodeFormer\venv\lib\site-packages\torch\onnx\utils.py", line 506, in export _export( File "d:\code\CodeFormer\venv\lib\site-packages\torch\onnx\utils.py", line 1548, in _export graph, params_dict, torch_out = _model_to_graph( File "d:\code\CodeFormer\venv\lib\site-packages\torch\onnx\utils.py", line 1113, in _model_to_graph graph, params, torch_out, module = _create_jit_graph(model, args) File "d:\code\CodeFormer\venv\lib\site-packages\torch\onnx\utils.py", line 989, in _create_jit_graph graph, torch_out = _trace_and_get_graph_from_model(model, args) File "d:\code\CodeFormer\venv\lib\site-packages\torch\onnx\utils.py", line 893, in _trace_and_get_graph_from_model trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph( File "d:\code\CodeFormer\venv\lib\site-packages\torch\jit_trace.py", line 1268, in _get_trace_graph outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs) File "d:\code\CodeFormer\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "d:\code\CodeFormer\venv\lib\site-packages\torch\jit_trace.py", line 127, in forward graph, out = torch._C._create_graph_by_tracing( File "d:\code\CodeFormer\venv\lib\site-packages\torch\jit_trace.py", line 118, in wrapper outs.append(self.inner(*trace_inputs)) File "d:\code\CodeFormer\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "d:\code\CodeFormer\venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward result = self.forward(*input, **kwargs) File "D:\code\CodeFormer\basicsr\archs\codeformer_arch.py", line 277, in forward x = self.fuse_convs_dict[f_size](enc_feat_dict[f_size].detach(), x, w) File "d:\code\CodeFormer\venv\lib\site-packages\torch\nn\modules\container.py", line 461, in **getitem** return self._modules[key] KeyError: 'tensor(32)'

Replace lines 275-278 in the code `basicsr/archs/codeformer_arch.py` with the following:

```
f_size = str(int(x.shape[-1]))
f_size_ = str(x.shape[-1])
if w > 0:
    x = self.fuse_convs_dict[f_size](enc_feat_dict[f_size_].detach(), x, w)
```

**Comment by henbucuoshanghai** [comment]
ite-packages\torch\nn\modules\container.py", line 461, in getitem
return self._modules[key]
KeyError: 'tensor(32)

why ？


f_size = str(int(x.shape[-1]))
f_size_ = str(x.shape[-1])

not worked

**Comment by Royalvice** [comment]
> if w > 0:
>     x = self.fuse_convs_dict[f_size](enc_feat_dict[f_size_].detach(), x, w)

if w > 0:
    x = self.fuse_convs_dict[f_size](enc_feat_dict[f_size_].detach(), x, w) Have you add this?

**Comment by Royalvice** [comment]
> ite-packages\torch\nn\modules\container.py", line 461, in getitem return self._modules[key] KeyError: 'tensor(32)
> 
> why ？
> 
> f_size = str(int(x.shape[-1])) f_size_ = str(x.shape[-1])
> 
> not worked

I have exported onnx successfully

**Comment by instant-high** [comment]
Maybe this is helpful:
https://github.com/harisreedhar/Face-Upscalers-ONNX

**Comment by henbucuoshanghai** [comment]
@Royalvice   the onnx model works well?

**Comment by Royalvice** [comment]
> @Royalvice the onnx model works well?

yes

**Comment by henbucuoshanghai** [comment]
get the onnx model and run it,with this error


Failed inference for CodeFormer: 'Tensor' object has no attribute 'keys'

**Comment by henbucuoshanghai** [comment]
the resout of onnx and pth  has a little different？why
pth is 0.0688 and onnx is 0.061. 0.0271 vs 0.0251,-0.0468 vs -0.0440.
is it ok?

**Comment by henbucuoshanghai** [comment]
the  resout of pth and onnx is different...why

**Comment by henbucuoshanghai** [comment]
can u share your onnx  model? tks
