### ISSUE TITLE
cant recognize RealESRGAN on gpu

### ISSUE THREAD

**Issue by geowjm** [sczhou/CodeFormer#26]
how can i fix this? thank you!

`RuntimeWarning: The unoptimized RealESRGAN is slow on CPU. We do not use it. If you really want to use it, please modify the corresponding codes.
warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '`

**Comment by sczhou** [comment]
Refer to https://github.com/sczhou/CodeFormer/issues/23
