### ISSUE TITLE
Reproducing Codeformer

### ISSUE THREAD

**Issue by jameelhassan** [sczhou/CodeFormer#261]
Hi, 

I wanted to reproduce the model. As a first step, I have attempted training Stage 2 of the model using the VQGAN pre-trained weights from Stage 1 given [here](https://github.com/sczhou/CodeFormer/releases/tag/v0.1.0). However, the results I get at the end of Stage 2, using the inference script with w=0 are not good. 
"python inference_codeformer.py -w 0.0 --input_path inputs/cropped_faces/0143.png"

I have attached samples of the results I get. The dataset is prepared using the crop_and_align.py script, resized to 512x512. I use the exact same config file provided except for reducing the number of GPUs to 4 but doubling the batch_size per GPU to stay consistent on effective batch_size. I have attached my training log file as well.

![500k_0143](https://github.com/sczhou/CodeFormer/assets/40886131/bbe03b6f-1f12-4e9c-9dd6-00dbf45b65b9)
![500k_0240](https://github.com/sczhou/CodeFormer/assets/40886131/8e1d270e-4c49-4a39-9b66-a26fb1e948bb)

Could you kindly try to reproduce the work from your end and confirm, or let me know if I am doing something wrong? Given the potential of this work, it would be very useful for many researchers ahead to be able to easily reproduce this. There have been multiple comments on GitHub of people attempting to reproduce the work, but are having sub-par performance. 

[train_20230620_110600_CodeFormer_stage2_4GPU.log](https://github.com/sczhou/CodeFormer/files/11955014/train_20230620_110600_CodeFormer_stage2_4GPU.log)

**Comment by jameelhassan** [comment]
I was not using ```latent_gt.pth``` but rather generating the ground truth during training. This seems to be the issue. It seems the copy of the VQGAN from stage 1 model weights is not loaded to the model, so the ground truth is incorrect.

**Comment by Xrenya** [comment]
@jameelhassan you did not generated latent_gt_code1024.pth: `latent_gt_path: ~ # without pre-calculated latent code`, is it correct?

**Comment by Xrenya** [comment]
@jameelhassan Thank you, that's strange, since the results should be the same as using `latent_gt_code1024.pth`, since it is still calculate it during [training](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L91), I have also strange result on the second stage as well, while codebook gives fine results so far. Could you please post a sample using the updated second stage if it is possible?

**Comment by jameelhassan** [comment]
> I was not using `latent_gt.pth` but rather generating the ground truth during training. This seems to be the issue. It seems the copy of the VQGAN from stage 1 model weights is not loaded to the model, so the ground truth is incorrect.

@Xrenya as mentioned earlier, I noticed that the pre-trained weights of the VQGAN (which is used to generate the latent_gt) are not loaded to the model during Stage 2 training. Hence the error. I did not try retraining it after fixing it though. 

A sample image after Stage 2 training with w=0.0 is attached
![0143](https://github.com/sczhou/CodeFormer/assets/40886131/cc23ff96-5266-4dc3-a3b2-5927077d8262)

**Comment by Xrenya** [comment]
@jameelhassan oh, I found the issue, thank you, it helps a lot!

**Comment by JaywongWang** [comment]
Hi guys, have anyone successfully re-train stage-3 model? I can successfully re-train stage-1 and stage-2, but my re-trained stage-3 model performs unexpectedly (the resulted image is a almost a black image). And I noticed the d_weight is always 0 after several hundrend iterations.

**Comment by Xrenya** [comment]
@JaywongWang yes, I have able to retrain it, I had issue with loading model weight in codeformer_idx_model.py and codeformer_join_model.py: `self.hq_vqgan_fix`. In stage 3 I had to fix `w>=0` in line 276 in codeformer_arch.py

**Comment by JaywongWang** [comment]
> > @JaywongWang yes, I have able to retrain it, I had issue with loading model weight in codeformer_idx_model.py and codeformer_join_model.py: `self.hq_vqgan_fix`. In stage 3 I had to fix `w>=0` in line 276 in codeformer_arch.py
> 
> I have also already fix `w>=0`. I used my retrained VQGAN discriminator as pretrained discriminator in stage-3. I wonder if your retrained model also used your pretrained discriminator. I am trying to find out the difference with your retraining process.

@Xrenya Would you mind sharing your training details ?

**Comment by Xrenya** [comment]
@JaywongWang, I will write a little bit about what I have done so far to reproduce.
`options/CodeFormer_stage3.yml`: `latent_gt_path: ~ # without pre-calculated latent code`, I did not generate the pre-calculated gt, so I had to fix the issue with loading model to generate the ground truth since the model is build, but [not loaded](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49). The weights to build this model I have got from [here](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage2.yml#L64) so basically it is the same as for the second stage. This [weights](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L89) was taken from the first stage and this [one](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L86) from the second stage. After fixing this issue I got the normal results for the second stage after I fixed the same issue for the third stage and the last issue was `w>=0`. I have got black images on the second stage because the model did not generate appropriate ground truth, I think it is the same issue. If you have questions feel free to ask.

**Comment by JaywongWang** [comment]
> @JaywongWang, I will write a little bit about what I have done so far to reproduce. `options/CodeFormer_stage3.yml`: `latent_gt_path: ~ # without pre-calculated latent code`, I did not generate the pre-calculated gt, so I had to fix the issue with loading model to generate the ground truth since the model is build, but [not loaded](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49). The weights to build this model I have got from [here](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage2.yml#L64) so basically it is the same as for the second stage. This [weights](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L89) was taken from the first stage and this [one](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L86) from the second stage. After fixing this issue I got the normal results for the second stage after I fixed the same issue for the third stage and the last issue was `w>=0`. I have got black images on the second stage because the model did not generate appropriate ground truth, I think it is the same issue. If you have questions feel free to ask.

@Xrenya I am a little bit confused. Do you mean that you directly used the official models as your pre-trained stage-1 & stage-2 model, instead of training them by yourself? My re-trained stage-1 & stage-2 models perform normally, and my only issue is the stage-3 model retraining.

**Comment by JaywongWang** [comment]
> @JaywongWang, I will write a little bit about what I have done so far to reproduce. `options/CodeFormer_stage3.yml`: `latent_gt_path: ~ # without pre-calculated latent code`, I did not generate the pre-calculated gt, so I had to fix the issue with loading model to generate the ground truth since the model is build, but [not loaded](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49). The weights to build this model I have got from [here](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage2.yml#L64) so basically it is the same as for the second stage. This [weights](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L89) was taken from the first stage and this [one](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L86) from the second stage. After fixing this issue I got the normal results for the second stage after I fixed the same issue for the third stage and the last issue was `w>=0`. I have got black images on the second stage because the model did not generate appropriate ground truth, I think it is the same issue. If you have questions feel free to ask.

@Xrenya I generated pre-calculated gt and modify the corresponding latent_gt_path. You mentioned that previously your stage-2 retrained model did not generate appropriate ground truth, and I wonder why you previously failed to generate appropriate gt?

By the way, my current produced result from stage-3  model looks like this:
![result](https://github.com/sczhou/CodeFormer/assets/32317244/f7a2e316-e0bc-4c17-8995-c08e64671aeb)

**Comment by Xrenya** [comment]
@JaywongWang, no, I trained them from scratch, I found only these issues during the reproduction of the results. After fixing all the issues I have mentioned above I was able to get the stated results in his paper. Did you use pre-calculated latent code? If you do not use it, you should have to fix these issues: [1](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49), [2](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_joint_model.py#L52)

**Comment by JaywongWang** [comment]
> @JaywongWang, no, I trained them from scratch, I found only these issues during the reproduction of the results. After fixing all the issues I have mentioned above I was able to get the stated results in his paper. Did you use pre-calculated latent code? If you do not use it, you should have to fix these issues: [1](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49), [2](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_joint_model.py#L52)

@Xrenya Yes, I used pre-calculated latent code from my re-trained stage-1 VQGAN model.

**Comment by JaywongWang** [comment]
> @JaywongWang, no, I trained them from scratch, I found only these issues during the reproduction of the results. After fixing all the issues I have mentioned above I was able to get the stated results in his paper. Did you use pre-calculated latent code? If you do not use it, you should have to fix these issues: [1](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49), [2](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_joint_model.py#L52)

@Xrenya  I still do not understand the issues you mentioned, based on the links you privided. I do not see any difference with the original official code. So what code changes should I make except for the w>=0 ?

**Comment by Xrenya** [comment]
@JaywongWang , I did not use pre-calculated latent code, so I had to generate sample during the training:
```
self.hq_vqgan_fix = build_network(self.opt['network_vqgan']).to(self.device)

self.load_network(self.hq_vqgan_fix, load_path, self.opt['path'].get('strict_load_g', True), 'params_ema')

self.hq_vqgan_fix.eval()
```
in the code, it is never loaded pre-trained model, just built and set into inference mode, so I have to add extra line to load the model.
Could you post images from the first and second stages to verify that everything works fine?

**Comment by JaywongWang** [comment]
> > @JaywongWang , I did not use pre-calculated latent code, so I had to generate samples during the training:
> > ```
> > self.hq_vqgan_fix = build_network(self.opt['network_vqgan']).to(self.device)
> > 
> > self.load_network(self.hq_vqgan_fix, load_path, self.opt['path'].get('strict_load_g', True), 'params_ema')
> > 
> > self.hq_vqgan_fix.eval()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the code, it is never loaded pre-trained model, just built and set into inference mode, so I have to add extra line to load the model. Could you post images from the first and second stages to verify that everything works fine?
> 
> Oh, I get what you meant. I assumed the pre-trained weights are loaded through "network_g" config, where VQGAN pre-trained weights are included in the weights of "CodeFormer".
> 
> The following images are from stage-1 and stage-2 re-trained models, respectively.
> 
> ![00000_00](https://user-images.githubusercontent.com/32317244/268571354-6aa10a64-ce92-4aa8-9a3f-7f28cd9a5d85.png)
> 
> ![00000_00](https://user-images.githubusercontent.com/32317244/268571400-420830e0-5334-48a5-b565-cfc703f11850.png)

@Xrenya I think the VQGAN weights are not loaded since network_g is initialized first. I will try fixing this issue and then retraining the stage-3 model. Thank you so much for the very constructive suggestions!

**Comment by Xrenya** [comment]
@JaywongWang Yes, they are included in the config but never loaded for the generator model. In that case, don't use pre-calculated weights and set the model, so it will generate latents during the training.

**Comment by jameelhassan** [comment]
@Xrenya Do you mind sharing the training log of Stage 3? I fixed the stage 3 issues with loading VQGAN weights, but the results were not as good as CodeFormer released weights.

**Comment by Xrenya** [comment]
@jameelhassan Sorry, I didn't keep the logs, but can you post your logs and image output to review your results? Did you train it on your own dataset or did you use the FFHQ image dataset? But did you also fix the loading issue on stage 2?

**Comment by JaywongWang** [comment]
> load_path

I have carefully checked the codes, and I found that my training did not involve any network_vqgan issue, since latent_gt_path is set in both stage-2 and stage-3 training (and thus the self.hq_vqgan_fix was not built). So I am now still confusing.
BTW, if generating gt during training stage-3 model, the "load_path" in self.load_network(self.hq_vqgan_fix, load_path, self.opt['path'].get('strict_load_g', True), 'params_ema') should still be the stage-1 pre-trained path, right?
@Xrenya

**Comment by Xrenya** [comment]
@JaywongWang, no, at the first stage you are building the VQGAN model to generate HQ vectors for 2, and 3 stages. This issues only on second and third stages. What about your dataset for the second stage is processed correctly? Did you generate your vectors correctly, like your faces are already cropped and you run the file, after you set up the path for your latent vectors into config to be a ground truth?

**Comment by Xrenya** [comment]
@JaywongWang No, the model on the first stage is trained and does not load anything, also they use different file to load in config. I see, that strange since I did not change anything. Do you still have logs? I assume that you did [cropping](https://github.com/sczhou/CodeFormer/blob/master/scripts/crop_align_face.py) correctly, did you check that you uncomment that [config](https://github.com/sczhou/CodeFormer/blob/master/options/CodeFormer_stage3.yml) file line: `latent_gt_path: './experiments/pretrained_models/VQGAN/latent_gt_code1024.pth'`?

**Comment by JaywongWang** [comment]
> No, the model on the first stage is trained and does not load anything

@Xrenya Hi Xrenya, thank you for your great patience and kindness! 
I have tried the following two ways to reproduce:
(1) Generate latent code gt first using my re-trained VQGAN model, and config the latent_gt_path. The training log of stage-3 model is attached ([train_20230913_163254_CodeFormer_stage3.log](https://github.com/sczhou/CodeFormer/files/12654864/train_20230913_163254_CodeFormer_stage3.log)). The results are abnormal, and the loss terms d_weight and l_g_gan are zeros (or near zeros) during the whole training.
(2) Do not use pre-generated code gt, generate the latent code gt during training. Before training, modify the code so that the VQGAN pre-trained weights can be loaded into the built model (as you suggested). The training log of stage-3 model is attached ([train_20230919_013117_CodeFormer_stage3.log](https://github.com/sczhou/CodeFormer/files/12654866/train_20230919_013117_CodeFormer_stage3.log)). The intermediate results are also abnormal (the training has not finished, but I guess it will has the same issue).

**Comment by JaywongWang** [comment]
> @JaywongWang No, the model on the first stage is trained and does not load anything, also they use different file to load in config. I see, that strange since I did not change anything. Do you still have logs? I assume that you did [cropping](https://github.com/sczhou/CodeFormer/blob/master/scripts/crop_align_face.py) correctly, did you check that you uncomment that [config](https://github.com/sczhou/CodeFormer/blob/master/options/CodeFormer_stage3.yml) file line: `latent_gt_path: './experiments/pretrained_models/VQGAN/latent_gt_code1024.pth'`?

@Xrenya Also, I have also visualized the training samples (from left to right they are input, input_large_de, and gt). 
![1](https://github.com/sczhou/CodeFormer/assets/32317244/94cefe8b-8075-4d74-95b2-8e2428a80dc4)

**Comment by Xrenya** [comment]
@JaywongWang, could you test on your machine please this function because I cannot see that `LPIPS` is loaded, might be different version. Did you copy the vgg model's weights into `/.cache/torch/hub/checkpoints/`?
```
import lpips
perceptual = lpips.LPIPS(net="vgg", spatial=False).eval()

# output in cmd: Loading model from: /home/user/~/vgg.pth
```

**Comment by JaywongWang** [comment]
> @JaywongWang, could you test on your machine please this function because I cannot see that `LPIPS` is loaded, might be different version. Did you copy the vgg model's weights into `/.cache/torch/hub/checkpoints/`?
> 
> ```
> import lpips
> perceptual = lpips.LPIPS(net="vgg", spatial=False).eval()
> 
> # output in cmd: Loading model from: /home/user/~/vgg.pth
> ```

@Xrenya The test log is shown below. I can see the log showing that "Loss [LPIPSLoss] is created". 

![tt](https://github.com/sczhou/CodeFormer/assets/32317244/f7b6387b-5027-42b7-b1d8-fa14028aa728)

**Comment by Xrenya** [comment]
@JaywongWang, yes, I can see it, I didn't see the loading verbose from lpips about it in logs, but visible in your cmd. Currently, I cannot see any issue so far, I will check it later again

**Comment by JaywongWang** [comment]
> @JaywongWang, yes, I can see it, I didn't see the loading verbose from lpips about it in logs, but visible in your cmd. Currently, I cannot see any issue so far, I will check it later again

@Xrenya Hi Xrenya, which pytorch version did you use?

**Comment by Xrenya** [comment]
@JaywongWang 1.13.1+cu117

**Comment by JaywongWang** [comment]
> @JaywongWang 1.13.1+cu117

@Xrenya My torch version is 1.10.1+cu111 .

**Comment by JaywongWang** [comment]
@Xrenya Would you mind sharing your training config file for stage-3 ?

**Comment by Xrenya** [comment]
@JaywongWang Sorry, I can't access to server to retrieve data from it, but I have read your config file and looks the same

**Comment by Xrenya** [comment]
@JaywongWang, I haven't seen this problem, that's strange, maybe testing it with different version will help to find the issue

**Comment by order-a-lemonade** [comment]
@JaywongWang @Xrenya 
 hi, could you provide some reconstructed images of you re-trained stage -1? Now i am unable to reproduce stage-1, how many training iterations of your settings? i train 160w iterations(default in configs) and it takes me more than 15days on 8 v100 gpus.  Is this normal?

**Comment by JaywongWang** [comment]
> @JaywongWang @Xrenya hi, could you provide some reconstructed images of you re-trained stage -1? Now i am unable to reproduce stage-1, how many training iterations of your settings? i train 160w iterations(default in configs) and it takes me more than 15days on 8 v100 gpus. Is this normal?

@order-a-lemonade 

I only had GPUs with 24G memory, so I changed batch size from 4 to 2 and employed 8 GPUs for training (total batch size is 8*2=16). The number of training iterations are 30w. The reconstructed FFHQ images are normal. One sample is shown below (left: original FFHQ image, right: reconstructed FFHQ image).

![ffhq_vqgan_sample](https://github.com/sczhou/CodeFormer/assets/32317244/d728d1d4-0f91-40d5-a251-64f3d2c1118a)

**Comment by JaywongWang** [comment]
> @JaywongWang @Xrenya hi, could you provide some reconstructed images of you re-trained stage -1? Now i am unable to reproduce stage-1, how many training iterations of your settings? i train 160w iterations(default in configs) and it takes me more than 15days on 8 v100 gpus. Is this normal?

@order-a-lemonade It also took me 15 days using 8 GPUs.

**Comment by order-a-lemonade** [comment]
> > @JaywongWang @Xrenya hi, could you provide some reconstructed images of you re-trained stage -1? Now i am unable to reproduce stage-1, how many training iterations of your settings? i train 160w iterations(default in configs) and it takes me more than 15days on 8 v100 gpus. Is this normal?
> 
> @order-a-lemonade It also took me 15 days using 8 GPUs.

thanks a  lot!!!
maybe my editing of source code leads to my bad results.😢

**Comment by order-a-lemonade** [comment]
sure, if i get normal results for stage-3, i'll share with u. by the way, is your stage 3  based on your reproduced stage-1&2?

**Comment by order-a-lemonade** [comment]
> > > > @JaywongWang @Xrenya hi, could you provide some reconstructed images of you re-trained stage -1? Now i am unable to reproduce stage-1, how many training iterations of your settings? i train 160w iterations(default in configs) and it takes me more than 15days on 8 v100 gpus. Is this normal?
> > > 
> > > 
> > > @order-a-lemonade It also took me 15 days using 8 GPUs.
> > 
> > 
> > thanks a lot!!! maybe my editing of source code leads to my bad results.😢
> 
> @order-a-lemonade But until now I still cannot reproduce stage-3. Please let me know if you have normal results for stage-3.

sure, if i get normal results for stage-3, i'll share with u. by the way, is your stage 3 based on your reproduced stage-1&2? can you reproduce stage-3 using the weights provided by authors?

**Comment by JaywongWang** [comment]
> sure, if i get normal results for stage-3, i'll share with u. by the way, is your stage 3 based on your reproduced stage-1&2?

@order-a-lemonade Yes, it is based on my reproduced stage-1 & stage-2 model. The reproduced stage-1 and stage-2 both perform normally.

**Comment by order-a-lemonade** [comment]
> > sure, if i get normal results for stage-3, i'll share with u. by the way, is your stage 3 based on your reproduced stage-1&2?
> 
> @order-a-lemonade Yes, it is based on my reproduced stage-1 & stage-2 model. The reproduced stage-1 and stage-2 both perform normally.

get it

**Comment by qingzwang** [comment]
> @jameelhassan oh, I found the issue, thank you, it helps a lot!

In the codeformer_idx_mode.py line 48-53, you do not load the pretrained vqgan model. I think this the reason.

**Comment by cxcx1996** [comment]
> > @JaywongWang, I will write a little bit about what I have done so far to reproduce. `options/CodeFormer_stage3.yml`: `latent_gt_path: ~ # without pre-calculated latent code`, I did not generate the pre-calculated gt, so I had to fix the issue with loading model to generate the ground truth since the model is build, but [not loaded](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49). The weights to build this model I have got from [here](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage2.yml#L64) so basically it is the same as for the second stage. This [weights](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L89) was taken from the first stage and this [one](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L86) from the second stage. After fixing this issue I got the normal results for the second stage after I fixed the same issue for the third stage and the last issue was `w>=0`. I have got black images on the second stage because the model did not generate appropriate ground truth, I think it is the same issue. If you have questions feel free to ask.
> 
> @Xrenya I generated pre-calculated gt and modify the corresponding latent_gt_path. You mentioned that previously your stage-2 retrained model did not generate appropriate ground truth, and I wonder why you previously failed to generate appropriate gt?
> 
> By the way, my current produced result from stage-3 model looks like this: ![result](https://private-user-images.githubusercontent.com/32317244/268555306-f7a2e316-e0bc-4c17-8995-c08e64671aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjUyNzQsIm5iZiI6MTcwNDE2NDk3NCwicGF0aCI6Ii8zMjMxNzI0NC8yNjg1NTUzMDYtZjdhMmUzMTYtZTBiYy00YzE3LTg5OTUtYzA4ZTY0NjcxYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAzMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTNiNzBjYTVlN2UyZDhhZDA4N2Q3MjM5MjIxODhjMjIzN2M4OTE3YTUxMmY3NGVhNzdjNTNjNjA3Y2M5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xu2BILAPlAWVvdPgGzEGtT9wAW8VMrBBjp7J9V-K05g)

@JaywongWang . Hi, did you solve this problem? I think I meet the same problem with you. When I train stage3 loading by my trained stage2 model, the result is all gray like yours. But when I loaded the given pretrained stage2, the result of stage3  is good.

**Comment by JaywongWang** [comment]
> > > @JaywongWang, I will write a little bit about what I have done so far to reproduce. `options/CodeFormer_stage3.yml`: `latent_gt_path: ~ # without pre-calculated latent code`, I did not generate the pre-calculated gt, so I had to fix the issue with loading model to generate the ground truth since the model is build, but [not loaded](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/basicsr/models/codeformer_idx_model.py#L49). The weights to build this model I have got from [here](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage2.yml#L64) so basically it is the same as for the second stage. This [weights](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L89) was taken from the first stage and this [one](https://github.com/sczhou/CodeFormer/blob/8392d0334956108ab53d9439c4b9fc9c4af0d66d/options/CodeFormer_stage3.yml#L86) from the second stage. After fixing this issue I got the normal results for the second stage after I fixed the same issue for the third stage and the last issue was `w>=0`. I have got black images on the second stage because the model did not generate appropriate ground truth, I think it is the same issue. If you have questions feel free to ask.
> > 
> > 
> > @Xrenya I generated pre-calculated gt and modify the corresponding latent_gt_path. You mentioned that previously your stage-2 retrained model did not generate appropriate ground truth, and I wonder why you previously failed to generate appropriate gt?
> > By the way, my current produced result from stage-3 model looks like this: ![result](https://private-user-images.githubusercontent.com/32317244/268555306-f7a2e316-e0bc-4c17-8995-c08e64671aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjUyNzQsIm5iZiI6MTcwNDE2NDk3NCwicGF0aCI6Ii8zMjMxNzI0NC8yNjg1NTUzMDYtZjdhMmUzMTYtZTBiYy00YzE3LTg5OTUtYzA4ZTY0NjcxYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAzMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTNiNzBjYTVlN2UyZDhhZDA4N2Q3MjM5MjIxODhjMjIzN2M4OTE3YTUxMmY3NGVhNzdjNTNjNjA3Y2M5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xu2BILAPlAWVvdPgGzEGtT9wAW8VMrBBjp7J9V-K05g)
> 
> @JaywongWang . Hi, did you solve this problem? I think I meet the same problem with you. When I train stage3 loading by my trained stage2 model, the result is all gray like yours. But when I loaded the given pretrained stage2, the result of stage3 is good.

@cxcx1996 I have not found the solution.

**Comment by yeruiqian** [comment]
我可以复现第三阶段，但是当w>0时，会出现嘴唇或额头溢色问题，就像这个issue里面一样。https://github.com/sczhou/CodeFormer/issues/286

**Comment by milely** [comment]
> 我可以复现第三阶段，但是当w>0时，会出现嘴唇或额头溢色问题，就像这个issue里面一样。#286
哈喽，可以加个联系方式交流一下吗，我也在训练这个模型，我的邮箱是hapoqin@gmail.com，谢谢啦

**Comment by milely** [comment]
我使用自己的数据从头复现了3个阶段的训练，目前训练完成后w>0 没有出现嘴唇溢色的问题。官方开源的模型，在特定颜色的人脸背景下会出现嘴唇溢色的问题，所以猜测可能是数据分布的问题，官方开源的ffhq训练的，在亚洲人上推理时，眼睛偏向于欧美人的分布

**Comment by yeruiqian** [comment]
> 我使用自己的数据从头复现了3个阶段的训练，目前训练完成后w>0 没有出现嘴唇溢色的问题。官方开源的模型，在特定颜色的人脸背景下会出现嘴唇溢色的问题，所以猜测可能是数据分布的问题，官方开源的ffhq训练的，在亚洲人上推理时，眼睛偏向于欧美人的分布

我从官方第二阶段训练第三阶段，没有出现溢色问题，用自己训练的第二阶段出现的这个问题。可能是第一阶段codebook和decoder 出现问题，或者第二阶段的训练有问题。我没定位到，从头训练三个阶段没问题吗？请问你是使用官方配置文件，8卡训练的吗？

**Comment by milely** [comment]
> > 我使用自己的数据从头复现了3个阶段的训练，目前训练完成后w>0 没有出现嘴唇溢色的问题。官方开源的模型，在特定颜色的人脸背景下会出现嘴唇溢色的问题，所以猜测可能是数据分布的问题，官方开源的ffhq训练的，在亚洲人上推理时，眼睛偏向于欧美人的分布
> 
> 我从官方第二阶段训练第三阶段，没有出现溢色问题，用自己训练的第二阶段出现的这个问题。可能是第一阶段codebook和decoder 出现问题，或者第二阶段的训练有问题。我没定位到，从头训练三个阶段没问题吗？请问你是使用官方配置文件，8卡训练的吗？

我从头训练了3个阶段，codebook也改了一下，codebook看起来比官方的更鲁棒一些，重建质量更高。

**Comment by yeruiqian** [comment]
> > > 我用自己的数据从头复现了3个阶段的训练，目前训练完成后w>0没有出现嘴唇溢色的问题。官方开源的模型，在特定颜色的人脸下会背景出现嘴唇溢色的问题，所以猜测可能是数据分布的问题，官方开源的ffhq训练的，在亚洲人上推理时，偏向于欧美人的分布
> > 
> > 
> > 我从官方第二阶段训练第三阶段，没有出现溢色问题，用自己训练的第二阶段出现这个问题。可能是第一阶段密码书和解码器出现问题，或者第二阶段训练有问题。我没定位到，从头训练三个阶段没问题吗？请问您是使用官方配置文件，8卡训练的吗？
> 
> 我从头训练了3个阶段，密码本也改了一下，密码本看起来比官方的更鲁棒一些，重建质量更高。
噢明白了，谢谢你的回复，看来是我的codebook不够鲁棒，导致出现溢色问题。
