### ISSUE TITLE
I can't improve the photo

### ISSUE THREAD

**Issue by psilooo777** [sczhou/CodeFormer#27]
![IMG_20220905_161424_678](https://user-images.githubusercontent.com/53978505/188458399-fb19c334-f15b-46b8-be89-7058fe9b51f1.jpg)
![IMG_20220905_161427_882](https://user-images.githubusercontent.com/53978505/188458403-6912ca0e-1f77-4ecd-8f52-4a89f4896a1b.jpg)
![IMG_20220905_161443_853](https://user-images.githubusercontent.com/53978505/188458405-5365e816-96f9-4b7e-9589-d9ebb46f09dc.jpg)

Hi, sometimes there are photos that the algorithm can't handle.
1 original photo. 2 photos - your algorithm w 1.0. 3 photos gfpgan 1.3
I tried different W settings, I could not get an acceptable result, try it yourself.

Another difficult photo that no algorithm could make
![IMG_20220905_162203_277](https://user-images.githubusercontent.com/53978505/188459616-751c4aca-d62f-4046-8e96-4b7215b8fa9d.jpg)

Try to improve these photos or the algorithm will not be able to do it ? Thanks

**Comment by sczhou** [comment]
You may like to try our new online demo in Replicate:
https://replicate.com/cjwbw/codeformer
