### ISSUE TITLE
The image under final_result is not clear but the restored_faces are clear

### ISSUE THREAD

**Issue by fomohodl2022** [sczhou/CodeFormer#274]
I tried the repo. It is very good.
However, it is strange that the images under final_results are not clear but the images under restored_faces are clear.

`python inference_codeformer.py -w 0.7 --input_path ./inputs/whole_imgs/00.jpg`

final_results
![00](https://github.com/sczhou/CodeFormer/assets/140383824/5425d0ab-34c9-4a82-a69f-93442d071d6c)

restored_faces
![00_01](https://github.com/sczhou/CodeFormer/assets/140383824/6d6b0367-04ed-4091-98b8-d74bd4691ae0)
![00_02](https://github.com/sczhou/CodeFormer/assets/140383824/42aaeb1c-4271-4129-a762-8670f841dfb7)
![00_03](https://github.com/sczhou/CodeFormer/assets/140383824/005ca079-6a66-443e-993f-09b26524bd84)

![00_00](https://github.com/sczhou/CodeFormer/assets/140383824/1609ce16-5c7c-4b28-9bed-f0cbcd2d5e9b)

**Comment by phong-phuong** [comment]
Hi,

The reason your background is unclear is because you need to add the background upsampling parameters when running the appliction:  --bg_upsampler realergan

For example:
```
python .\inference_codeformer.py -w 0.7 --bg_upsampler realesrgan --input_path inputs/whole_imgs 
```

**Comment by phong-phuong** [comment]
That is not the expected result. Mine comes out clear, including the faces. Yours is coming out with the background clear, but the faces haven't been swapped yet.

You can try running the command again.

**Comment by fomohodl2022** [comment]
I just tried but still no hope...
Do you think it is related to python or model version?

Logs
![Screenshot 2023-08-02 at 5 42 59 PM](https://github.com/sczhou/CodeFormer/assets/140383824/486f0a64-a86a-4258-ae4c-0f049427ed62)

Other results:
![00](https://github.com/sczhou/CodeFormer/assets/140383824/952b0368-18e1-4d5c-831e-615e1d64fc0b)
![01](https://github.com/sczhou/CodeFormer/assets/140383824/a8b0920e-ae2f-43a5-99a0-3546672f8278)
![02](https://github.com/sczhou/CodeFormer/assets/140383824/02c74eee-00e4-4ec0-8ffd-c52ad059ce43)
![03](https://github.com/sczhou/CodeFormer/assets/140383824/cd9f3425-7ec7-4bd8-b58c-b564c68b78b1)
![04](https://github.com/sczhou/CodeFormer/assets/140383824/550fd0e5-921e-4f39-8c29-872347a12ec4)
![05](https://github.com/sczhou/CodeFormer/assets/140383824/f70e0f26-4578-42c4-b444-f785b5430d7f)
![06](https://github.com/sczhou/CodeFormer/assets/140383824/b7686f46-38d0-45ce-b729-2e5a1202f047)

**Comment by phong-phuong** [comment]
Might be the model. You could try redownloading it.
Another thing is, when I recently installed this, in /scripts/crop_align_face.py, I remember I had to update two lines in the code to use:
```
PIL.Image.LANCZOS
```
instead PIL.Image.ANTIALIAS due to the error:

```[module 'PIL.Image' has no attribute 'ANTIALIAS' - ...](https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias)```

Do you remember if you changed those lines too? And if you are using something other than PIL.Image.LANCZOS?

**Comment by phong-phuong** [comment]
Sorry, ignore my previous reply, since your first post already proves that the face restoration model is working on your machine.
Instead, you can troubleshoot by:

- Inspecting the console logs to see if there were any errors.
- Delete the images in the /results folder
- Ensure the input images have not been modified
- Try running it on your own set of images

The python version I used is 3.10.

**Comment by fomohodl2022** [comment]
Thanks for your reply but still not working.
 I tried:
- re-download the model
- use my own set of input images
- delete ./results
- change the code PIL.Image.LANCZOS
- change from python 3.8 to python 3.9 (I tried 3.10 but it has dependency error)

May I know what's your device information?
Window? Mac (Intel or M1 or M2)?
Did you try with latest commit from this repo?
Conda version?

Again. Thanks for help.

**Comment by phong-phuong** [comment]
Windows. I cloned the repo earlier late last week. I have not fetched any new updates yet.

Worth fetching updates if you have not already, in case there was a recent fix. Maybe a computer restart might fix. I'm out of ideas.
Good luck.

I installed it without conda, but using pip in a virtual environment using: pip -m venv venv
Then install the requirements and add torch.

**Comment by fomohodl2022** [comment]
Big thanks for your help!!!
My problem is solved with your information.

I tried with non-anaconda python and it works!
Thanks a lot.

**Comment by GIT-LZL629** [comment]
> Big thanks for your help!!! My problem is solved with your information.
> 
> I tried with non-anaconda python and it works! Thanks a lot.

Can you tell me how to fix the clearance inconsistency between the final results and restored faces?
