### ISSUE TITLE
Weight initialization

### ISSUE THREAD

**Issue by andreaferretti** [sczhou/CodeFormer#29]
I see that [here](https://github.com/sczhou/CodeFormer/blob/master/basicsr/archs/codeformer_arch.py#L210-L217) there is some logic to initialize weights, but it only covers certain types of layers - in particular, it does not cover `Conv2d`. What kind of initialization do you use for other layers?

**Comment by sczhou** [comment]
PyTorch has built-in weight initialization for different layers, which works quite well so we didn't initialize other layers.

E.g., you can check the default initialization of the [Conv layer](https://github.com/pytorch/pytorch/blob/9cf62a4b5d3b287442e70c0c560a8e21d8c3b189/torch/nn/modules/conv.py#L111) and [Linear layer](https://github.com/pytorch/pytorch/blob/9cf62a4b5d3b287442e70c0c560a8e21d8c3b189/torch/nn/modules/linear.py#L168).

**Comment by andreaferretti** [comment]
Great, thank you!
