### ISSUE TITLE
PyTorch nightly error

### ISSUE THREAD

**Issue by seliquity** [sczhou/CodeFormer#30]
On PyTorch nightly I get the error:

`ValueError: invalid literal for int() with base 10: 'dev20220909'`

Looks like torch.__version__. returns dev20220909 and IS_HIGH_VERSION is expecting a semver?

**Comment by sczhou** [comment]
We need to get the version of Pytorch in https://github.com/sczhou/CodeFormer/blob/master/facelib/detection/yolov5face/face_detector.py#L20

I guess the error could be caused by no version number of nightly Pytorch. You'd like to switch to a stable version of Pytorch.
