### ISSUE TITLE
Black and white photos become colourized 

### ISSUE THREAD

**Issue by caacoe** [sczhou/CodeFormer#32]
Hi.

Do you think it would be possible to detect whether an image is black and white and desturate combined results in the event that they are? 

I imagine it would be more difficult to achieve this for sepia images though.

Thank you for your work.

**Comment by sczhou** [comment]
Hi, could you provide a Gary image sample here? I will have a test.

**Comment by caacoe** [comment]
![00329-1874259155-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759614-c09544d4-88a6-44bb-91eb-3b14fb91f063.png)
![00325-2875622194-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759619-0aed5686-4ebd-4339-be8a-f8cdda9d487a.png)
![00324-2875622194-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759622-aefefe32-5854-49e2-9b88-543a4698b384.png)
![00331-1874259155-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759624-5ca5aa33-26d5-405e-bdd1-1e6abc0445bc.png)
![00332-140506432-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759940-a0e034fc-e680-4e73-8f3e-acba0ab8121d.png)
![00333-140506432-pretty attractive beautiful young japanese woman looking into facing the camera, heavy makeup, portrait, low key, dramatic light](https://user-images.githubusercontent.com/110500565/189759944-2c62c55c-b208-4d7f-aa71-5f525b5615c6.png)

Here are ome examples

**Comment by sczhou** [comment]
Hi @caacoe, this issue is fixed. Please check the following result:

![000_out](https://user-images.githubusercontent.com/14334509/190058514-5a210e77-ae74-4771-856c-0ad76a8bfbda.png)
