### ISSUE TITLE
Use of regularization

### ISSUE THREAD

**Issue by NicolaGugole** [sczhou/CodeFormer#33]
Hi.

Thanks for the amazing work!
I have not seen anything regarding the use of regularization like L2 while developing the model, do you use it during training? Or have you anyway tried it to then discard the idea?

**Comment by sczhou** [comment]
Hi, we didn't use any network regularization during our training. Thanks!

**Comment by NicolaGugole** [comment]
Cool actually. Academically you always get the message of applying regularization so I would have expected at least an attempt in that direction. May I ask you if there is a particular reason following why you decided to not attempt it?

**Comment by sczhou** [comment]
Sorry for the late reply. We didn't try this since the training for Stages I and II are quite stable in our experiments.
