### ISSUE TITLE
I set w>=0 ,Stage 3 training to 120k but still reporting an error

### ISSUE THREAD

**Issue by create-li** [sczhou/CodeFormer#330]
I also encountered the same mistake. Modifying w>=0 or reporting an error. It's because I saved the weights from the previous one, which is 115k iterations of pre training. Do we need to retrain from the 0th iteration?

**Comment by hongdthaui** [comment]
Can you send link file edited w>=0 ?

**Comment by create-li** [comment]
Solved, needs to modify Python lib site_ Files in package
