### ISSUE TITLE
Results are not saved to disk post-inference

### ISSUE THREAD

**Issue by VisionaryMind** [sczhou/CodeFormer#37]
Running the `inference_codefomer.py` without errors, however at the end when it displays the message "all results are saved in results", the results directory is empty. No error, just an empty directory. Have you run into this issue before?

**Comment by geocine** [comment]
@VisionaryMind  how did you solve this? I am experiencing the same thing

**Comment by wesleywil** [comment]
Put the image or images inside the folder inputs/whole_imgs and run the command `python inference_codeformer.py -w 0.5`
