### ISSUE TITLE
Save some money on spaces

### ISSUE THREAD

**Issue by Inferencer** [sczhou/CodeFormer#379]
On Hugging face you have a space running on a T4, Hugging face now offers ZeroGPU (A100 40gb) option for free for pro users at $9 per month
https://huggingface.co/spaces/sczhou/CodeFormer

not sure how much your space is being used but figure it could save you some cash

**Comment by theparitt** [comment]
Don't spend money on this. I tested it with various pictures, and very few of them worked. I can say 2 out of 10 will give good results; the rest are quite bad.

**Comment by Inferencer** [comment]
my point was the space host (the repo owner) and was spending alot of money keeping an online demo alive
