### ISSUE TITLE
about eq.6 in the paper

### ISSUE THREAD

**Issue by tzm-tora** [sczhou/CodeFormer#39]
Hi, thank you for your excellent work.
I have a question when I read your paper.
the latter part of eq.6 is 
![捕获](https://user-images.githubusercontent.com/33857381/192972947-fd94892e-b5ae-402a-87ce-c418355b849c.PNG)
but you said that this loss is used to force the LQ feature Zl to approach the quantized feature Zc.
I cannot understand the relationship between Zh in eq.6 and Zl.
Could you explain how to get Zh in eq.6 or the definition of Zh?
Thank you.

**Comment by sczhou** [comment]
There is a typo in Eq.6, the $Z_h$ should be $Z_l$, which is the feature of the LQ image. We will fix this typo in our camera ready. Thanks!

**Comment by tzm-tora** [comment]
I understood, thank you!
