### ISSUE TITLE
face alignment doesnt work quite often even on front views

### ISSUE THREAD

**Issue by 2blackbar** [sczhou/CodeFormer#4]
Id switch it to something else because current alignment code is not working too well, it doesnt detect faces quite often so inference fails

**Comment by sczhou** [comment]
Hi @2blackbar, thanks for your feedback!

Actually, the face detection works well on old photos in my own testing, except for the faces that are extremely degraded. Could you post some failure cases where faces cannot be detected? So that I can check this issue, and can change a new face detection method if needed. Thanks.

**Comment by egorpezdir** [comment]
Hi @sczhou. I also encountered false face detection. With [this](https://cdn.discordapp.com/attachments/676022033921867776/999650608363606166/sevilja-1200.jpg) image for example it only detects 2 faces.

**Comment by sczhou** [comment]
Hi @2blackbar, you can indicate `upsample_num_times=2` in the inference command when the resolution for each face is small. By doing so, it could detect 16 faces in your provided image.

I know this is not the best solution, I'd try to update the detection method for a more smooth run.

**Comment by egorpezdir** [comment]
> Hi @2blackbar, you can indicate `--upsample_num_times 2` in the inference command when the resolution for each face is small. By doing so, it could detect 16 faces in your provided image.
> 
> I know this is not the best solution, I'd try to update the detection method for a more smooth run.

this works yes, thank you

**Comment by sczhou** [comment]
Hi all, we have updated the face detector, now we included 4 detection networks:
- large models: 'YOLOv5l'   'retinaface_resnet50'
- small models: 'YOLOv5n'   'retinaface_mobile0.25'

We set `det_model = 'YOLOv5l'` by default, you also can try other ones for your inference.
