### ISSUE TITLE
Testing Datasets

### ISSUE THREAD

**Issue by achusky** [sczhou/CodeFormer#42]
Hi.
Thanks for the awesome work.

How could I get the testing datasets (e.g., CelebA-Test, WIDER-Test) used in your paper?

**Comment by sczhou** [comment]
Thanks.
You can download WIDER-Test from this link: https://drive.google.com/file/d/1g05U86QGqnlN_v9SRRKDTU8033yvQNEa/view
Other test datasets can be found at https://xinntao.github.io/projects/gfpgan
