### ISSUE TITLE
When i use gfpgan everything is good , but when i choose codefomer i get this error :

### ISSUE THREAD

**Issue by Zmax15** [sczhou/CodeFormer#50]
![16657144634387884597709388970936](https://user-images.githubusercontent.com/115262260/195748241-e9f1cea4-0427-44ba-ad15-17a28a7259a0.jpg)

**Comment by sczhou** [comment]
There could be a model loading error in stable-diffusion-webui, please report this issue under their GitHub repo since our CodeFormer repo doesn't have this error.

**Comment by sczhou** [comment]
@Zmax15 Instead, you can use our code or online demo (https://huggingface.co/spaces/sczhou/CodeFormer) until they fix this bug.
