### ISSUE TITLE
No Upscale on Colab

### ISSUE THREAD

**Issue by estelen** [sczhou/CodeFormer#54]
Hi would it be possible to please add an Upscale feature on the Codeformer Google Colab? The Demo on Hugging Face and Replicate have one but not on Colab. Would love one on Colab if possible. I've tried to add one myself but I'm an idiot. Thanks in advance :)

**Comment by sczhou** [comment]
@estelen `FACE_UPSAMPLE` has been already added. You may need to check the new version.

**Comment by WASasquatch** [comment]
> @estelen `FACE_UPSAMPLE` has been already added. You may need to check the new version.

I think he means actual image upscaling. It wasn't part of your example Colab. I added it to that forked notebook I linked above. Feel free to use it if you want.
