### ISSUE TITLE
Option to use realesr-general-x4v3 model for backgrounds?

### ISSUE THREAD

**Issue by AIisCool** [sczhou/CodeFormer#57]
Could it be possible to set this newer model for backgrounds? It does a better job than RealESRGAN_x2plus. https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.3.0

**Comment by sczhou** [comment]
Thanks for your suggestions, but we are not planning to involve other new models for backgrounds. We will have a better background model of our own (which will be released soon), please stay tuned.
