### ISSUE TITLE
global exception OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4054: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'

### ISSUE THREAD

**Issue by liudonghua123** [sczhou/CodeFormer#58]
I checked `Background_Enhance` and `Face_Upsample` in the webpage of http://127.0.0.1:7860/ after running `python app.py`.

![image](https://user-images.githubusercontent.com/2276718/198447183-5ffce43a-80ea-446e-90c7-39ee6ba6d79e.png)

But after a few miniutes later, I got the following errors on the console. Nothing else errors shown.

```
D:\code\python\CodeFormer>python app.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
        detect 52 faces
global exception OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4054: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'


```

**Comment by sczhou** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/14334509/198483750-fa3db01a-d9e6-4291-b440-926a69fb8ae8.png">

The `Recaling_factor` must be an int value that is >0. 

Set it as 1 or 2, and try again.
