### ISSUE TITLE
Have no result, CodeFormer just run quick and stop

### ISSUE THREAD

**Issue by paperben** [sczhou/CodeFormer#64]
Hi everyone,

First my apologize for my english, i learn everyday and don't want to use the Google Trad P

So, yes, i have an issue with my newly installed CodeFormer.
Using Esrgan and Gfpgan for month with no issues and i wanted to discover other face restoration method. I installed all the stuff and have all the dependencies, i think...

So everytime i started the inference im getting with this :

**D:\CodeFormer>python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 0.7 --input_path inputs
Face detection model: retinaface_resnet50
Background upsampling: True, Face upsampling: True
All results are saved in results/inputs_0.7**

No results were saved, it just ended so. I tested a few Nvidia drivers, tested on the C drive, nothing change. What things im a missing ?

Thank you, Best regards

Ben

**Ryzen 5 3600X
GTX 1070Ti
Windows 10 last update
Last Nvidia drivers
CUDA 11.7
Python 3.8
Pytorch 1.13**

**Comment by sczhou** [comment]
@paperben Did you check if the input path is correct? It seems there is no input image in your given `inputs` path.

**Comment by paperben** [comment]
Hi,

Ok i double check and the issue was the picture extention.... it looks like it dont work with .jpeg or png. But jpg works. Thank you for the quick answer.

**Comment by paperben** [comment]
Tested with some new pictures in **png** and it works. Exist a compatible extensions list ?

**Comment by sczhou** [comment]
Only png and jpg formats are supported currently.
