### ISSUE TITLE
Expand face restoration area

### ISSUE THREAD

**Issue by lucellent** [sczhou/CodeFormer#67]
Would it be possible to expand the face enhancement so that it doesn't cut half of the hair every time? 
I understand this is probably dataset issue but it's annoying that it only enhances the face fully, the hair and the area around the face often gets half/half enhancement

<img width="281" alt="Screenshot_5" src="https://user-images.githubusercontent.com/38135928/202287157-6e223d3c-070b-486f-beee-929a8aee707a.png">

**Comment by sczhou** [comment]
This is a strategy for face-background fusion. Our current fusion strategy gives priority to the frontal face and chooses an optimal solution. While boundary blurs occasionally occur for some side faces, we don't have a better method for these cases yet.
