### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED on inference colab

### ISSUE THREAD

**Issue by robbsaber** [sczhou/CodeFormer#7]
I get this error : 

Processing: 00.jpg
Traceback (most recent call last):
  File "inference_codeformer.py", line 83, in <module>
    img_path, upsample_num_times=args.upsample_num_times, only_keep_largest=args.only_keep_largest)
  File "/content/CodeFormer/basicsr/utils/face_util.py", line 70, in detect_faces
    det_faces = self.face_detector(self.input_img, upsample_num_times)
RuntimeError: Error while calling cudnnConvolutionBiasActivationForward( context(), &alpha1, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &alpha2, out_desc, out, descriptor(biases), biases.device(), identity_activation_descriptor(), out_desc, out) in file /tmp/pip-install-uwm3abyj/dlib_961ff087af364da4874d302ad406612d/dlib/cuda/cudnn_dlibapi.cpp:1237. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED

**Comment by sczhou** [comment]
Sorry, I have no idea about this error, and other users do not seem to encounter this error before. Maybe you could check the versions of PyTorch and cuDNN of your CoLab. And I notice this issue appears in the face detector, I will switch it to a better detector these two days due to the fail detection issue, you can try it again then.

**Comment by robbsaber** [comment]
cuDNN version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

Pytorch 
1.12.0+cu113

**Comment by sczhou** [comment]
Hi @robbsaber, I updated the face detector, I guess it could solve your problem, please try it out. :hugs:

**Comment by robbsaber** [comment]
This worked. Thanks!
