### ISSUE TITLE
Error CUDA out of memory.

### ISSUE THREAD

**Issue by idanka** [sczhou/CodeFormer#78]
**Pls howto fix memory error?**
"Error CUDA out of memory. Tried to allocate 930.00 MiB (GPU 0; 3.82 GiB total capacity; 849.56 MiB already allocated; 938.75 MiB free; 1.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

Ubuntu 20.04.5 LTS / or Fedora 37 (rpmfusion cuda 11.7)
nVidia 1650
Anaconda3-2022.10-Linux-x86_64.sh (conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia)

1-2 workflows and errors, last image size 600*900 and missing image output.

**Comment by idanka** [comment]
Thx!

**Comment by joetech** [comment]
I still get this error and just grabbed the latest version today with the latest commits in my local copy.

**Comment by idanka** [comment]
> I still get this error and just grabbed the latest version today with the latest commits in my local copy.

- a black-and-white image must be converted to grayscale
- I reduced the size of the original image by 80%, if it is not enough, I reduce it again by 80%
- can't use shared memory, system includes 16 Gb RAM?
- could it be faulty memory management (anaconda, cuda, cudnn, pytorch)?

**Comment by joetech** [comment]
> * a black-and-white image must be converted to grayscale
I will try this

> * I reduced the size of the original image by 80%, if it is not enough, I reduce it again by 80%
My issue is happening while working with video that is only 2.4MB, but I'll keep this in mind.

> * can't use shared memory, system includes 16 Gb RAM?
This computer has not been upgraded in a long time and only has 8 GB of RAM.  I have been thinking for a while about upgrading.

> * could it be faulty memory management (anaconda, cuda, cudnn, pytorch)?
I'm guessing it's more about me being new at this and my computer being old.  I'll look at some of the above and then try again.

Thank you for the reply.

**Comment by idanka** [comment]
> * My issue is happening while working with video that is only 2.4MB, but I'll keep this in mind.

1. sample export video to *.png (and audio)

- ffmpeg -i 05.mp4 -ss 00:00:00 -t 00:03:20 -r 25 -f image2 img/%06d.png
- ffmpeg -i zig.mp4 -ss 00:00:00 -t 00:03:27 -r 29.97 -f image2 img/%06d.png
- ffmpeg -i zig.mov -ss 00:00:00 -t 00:03:27 -r 59.94 -f image2 img/%06d.png
- ffmpeg -i zig.mp4 -ss 00:00:00 -t 00:03:27 audio.aac

2. upscale sample

- python inference_codeformer.py --bg_upsampler realesrgan --face_upsample -w 1.0 --input_path ./img --save_video_fps 59.94 --upscale 2

3.   sample export video+audio (copy all image to img2x map)
-ffmpeg -f image2 -framerate 25 -i img2x/%06d.png -i audio.eac3 -r 60 -vcodec libx264 -crf 10 -preset veryslow -tune film video.mp4
-ffmpeg -f image2 -framerate 25 -i img2x/%04d_[L2][x2.67].png -i audio-1.ac3 -r 60 -vcodec libx264 -crf 16 video-w0.mp4

**Comment by idanka** [comment]
Linux add line .bashrc and restart os. 
Definitely slower but it works!

`export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256'`
