### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_uploadFiles')

### ISSUE THREAD

**Issue by capacle** [sczhou/CodeFormer#8]
Step 4 on Google Colab

```
MessageError                              Traceback (most recent call last)
[<ipython-input-7-dd9625c8d7bb>](https://localhost:8080/#) in <module>()
     10 os.mkdir(upload_folder)
     11 
---> 12 uploaded = files.upload()
     13 for filename in uploaded.keys():
     14   dst_path = os.path.join(upload_folder, filename)

3 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/files.py](https://localhost:8080/#) in upload()
     39   """
     40 
---> 41   uploaded_files = _upload_files(multiple=True)
     42   # Mapping from original filename to filename as saved locally.
     43   local_filenames = dict()

[/usr/local/lib/python3.7/dist-packages/google/colab/files.py](https://localhost:8080/#) in _upload_files(multiple)
    116   result = _output.eval_js(
    117       'google.colab._files._uploadFiles("{input_id}", "{output_id}")'.format(
--> 118           input_id=input_id, output_id=output_id))
    119   files = _collections.defaultdict(bytes)
    120 

[/usr/local/lib/python3.7/dist-packages/google/colab/output/_js.py](https://localhost:8080/#) in eval_js(script, ignore_result, timeout_sec)
     38   if ignore_result:
     39     return
---> 40   return _message.read_reply_from_input(request_id, timeout_sec)
     41 
     42 

[/usr/local/lib/python3.7/dist-packages/google/colab/_message.py](https://localhost:8080/#) in read_reply_from_input(message_id, timeout_sec)
    100         reply.get('colab_msg_id') == message_id):
    101       if 'error' in reply:
--> 102         raise MessageError(reply['error'])
    103       return reply.get('data', None)
    104 

MessageError: TypeError: Cannot read properties of undefined (reading '_uploadFiles')
```

**Comment by sczhou** [comment]
I didn't encounter this error, you could try to turn down the shield of your browser if it is open.
Please check more possible solutions here: https://stackoverflow.com/questions/48048279/typeerror-cannot-read-property-uploadfiles-of-undefined-in-google-colaborato

**Comment by capacle** [comment]
Thank you for your fast reply. Tried all the techniques. Now I get the same error on steps 3 and 4. Steps 2 runs fine. Also checked with other people, they are having the same issue.

`RuntimeError: Error while calling cudnnConvolutionBiasActivationForward( context(), &alpha1, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &alpha2, out_desc, out, descriptor(biases), biases.device(), identity_activation_descriptor(), out_desc, out) in file /tmp/pip-install-uwm3abyj/dlib_961ff087af364da4874d302ad406612d/dlib/cuda/cudnn_dlibapi.cpp:1237. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED`

**Comment by sczhou** [comment]
> Thank you for your fast reply. Tried all the techniques. Now I get the same error on steps 3 and 4. Steps 2 runs fine. Also checked with other people, they are having the same issue.

I see, actually not all users have this issue. I don't know if it's because of different Colab settings in different regions, but I'm not sure. I'm trying to change the face detector to solve this issue. Please stay tuned and have a try later. 

Yet another alternative is to clone the repo locally and test it out right now :)

**Comment by sczhou** [comment]
Hi @capacle, I updated the face detector, I guess it could solve your problem, please try it out. :hugs:

**Comment by capacle** [comment]
It worked!

Colab is dropping connection all the time so it took me some time to test, but yes, it works!

Thank you, you are the best!
