### ISSUE TITLE
Spots on the photo.

### ISSUE THREAD

**Issue by s3men451** [sczhou/CodeFormer#81]
When I load an image into a script, I occasionally get spots on the photo.

With what it can be connected?

![image](https://user-images.githubusercontent.com/119653577/206475953-f46f778c-c0c6-4eae-8322-bc9043e51921.png)

**Comment by sczhou** [comment]
May I know if you got this result from the Hugging Face demo? If so, Hugging Face demo sometimes has this issue, it should be some errors in the current hugging face SDK, thus I have no idea about this issue. You can run it again to get a current result.
