### ISSUE TITLE
How to deal with the change of face ID?

### ISSUE THREAD

**Issue by hzluyali** [sczhou/CodeFormer#9]
Thank you very much for your release. It seems that the face ID of restored images is changed.

**Comment by sczhou** [comment]
Hi @hzluyali, this is always a challenging issue in the face restoration task, which is hard to handle large degradation and preserve the identity content with a single model. You might also have found this issue in the previous works. 

In this work, we try to relieve this issue with a controllable module that can slightly trade the quality and fidelity, please check it out in our paper. For inference, you could try to set `w=1` to produce a better-fidelity result.
