### ISSUE TITLE
Colab bug

### ISSUE THREAD

**Issue by StantheBrain** [sczhou/CodeFormer#95]
On Colab, CodeFormer_inference.ipynb
1 - if you start by following the procedure it works.
2- later if you connect to your drive and import in the user_upload folder some files, and you restart the procedure, it will pretend to have done the job and created the folder next to it, but it will do nothing, no render folder, no reworked images.
3- If you restart the environment and follow the procedure as in the beginning (1), while it was working, it will pretend to have done the job and created the folder opposite, but will do nothing, no render folder, no render, as in procedure 2.

Delete the environment, make a new copy, or restart the environment, doesn't change anything, try to upload files from its drive (for speed sake) and ask for a batch job, corrupts something at a level, which later will prevent CodeFormer_inference.ipynb to work!

I don't get it!

**Comment by sczhou** [comment]
Thanks for this sharing, but sorry I have no idea about this.
