### ISSUE TITLE
Convert this project to .exe?

### ISSUE THREAD

**Issue by s11005349** [sczhou/CodeFormer#96]
Hi
I'm having trouble using this project.
It always says the result is in /results folder, while there's no /results folder in the /CodeFormer folder.
Can you convert it to an exe file with some simple GUI, so people can use it easily?

**Comment by sczhou** [comment]
We have now released a web interface for our model, which can be accessed at https://huggingface.co/spaces/sczhou/CodeFormer.

It's simple to use and we encourage you to give it a try!
